<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur5_3dof_gz</name>
  <version>0.1.0</version>
  <description>Gazebo Harmonic simulation of the 3-DOF UR5 with PID control.</description>
  <maintainer email="itaigro@gmail.com">Itai Groisman</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <depend>ros_gz_sim</depend>
  <depend>gz_ros2_control</depend>
  <depend>robot_state_publisher</depend>
  <depend>controller_manager</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>effort_controllers</depend>
  <depend>position_controllers</depend>

  <depend>ur_description</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
